[package]
name = "pinv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
clap = { version = "3.2.22", features = ["derive", "unicode"] }
rusqlite = "0.28.0"
simple-error = "0.2.3"
